http:
  middlewares:
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: false
    security-headers:
      headers:
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        browserXssFilter: true
        frameDeny: true
  routers:
    dashboard:
      rule: "Host(`${TRAEFIK_HOST:-traefik.localhost}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      service: api@internal
      entryPoints:
        - web
      middlewares:
        - security-headers


